services:
  app1:
    build: ./app1
    image: anjalirachel/app1
    container_name: app1
    ports:
      - "6000:6000"
    volumes:
      - .:/app
    networks:
      - compose-networks

  app2:
    build: ./app2
    image: anjalirachel/app2
    container_name: app2
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    networks:
      - compose-networks

networks:
  compose-networks:
    driver: bridge
